apiVersion: v1
kind: PersistentVolume
metadata:
  name: prestashop-pv-1
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: prestashop-1
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prestashop-pv-2
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: prestashop-2
    fsType: ext4
