apiVersion: v1
kind: Service
metadata:
  name: prestashop-mysql
  labels:
    app: prestashop
spec:
  ports:
    - port: 3306
  selector:
    app: prestashop
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: prestashop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prestashop-mysql
  labels:
    app: prestashop
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prestashop
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        resources:
            requests:
                cpu: "50m"
            limits:
                cpu: "50m"
        env:
          # $ kubectl create secret generic mysql-pass --from-file=password.txt
          # make sure password.txt does not have a trailing newline
        - name: MYSQL_ROOT_PASSWORD
          value: "1234"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
