apiVersion: v1
kind: Service
metadata:
  name: prestashop
  labels:
    app: prestashop
spec:
  ports:
    - port: 80
  selector:
    app: prestashop
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ps-pv-claim
  labels:
    app: prestashop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prestashop
  labels:
    app: prestashop
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prestashop
        tier: frontend
    spec:
      containers:
      - image: prestashop/prestashop:latest
        name: prestashop
        env:
        - name: DB_SERVER
          value: prestashop-mysql
        - name: DB_PASSWD
          value: "1234"
        ports:
        - containerPort: 80
          name: prestashop
